// Code generated by MockGen. DO NOT EDIT.
// Source: bimdb/internal/database (interfaces: StorageLayerInterface)

// Package database is a generated GoMock package.
package database

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStorageLayerInterface is a mock of StorageLayerInterface interface.
type MockStorageLayerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStorageLayerInterfaceMockRecorder
}

// MockStorageLayerInterfaceMockRecorder is the mock recorder for MockStorageLayerInterface.
type MockStorageLayerInterfaceMockRecorder struct {
	mock *MockStorageLayerInterface
}

// NewMockStorageLayerInterface creates a new mock instance.
func NewMockStorageLayerInterface(ctrl *gomock.Controller) *MockStorageLayerInterface {
	mock := &MockStorageLayerInterface{ctrl: ctrl}
	mock.recorder = &MockStorageLayerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageLayerInterface) EXPECT() *MockStorageLayerInterfaceMockRecorder {
	return m.recorder
}

// Del mocks base method.
func (m *MockStorageLayerInterface) Del(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Del", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Del indicates an expected call of Del.
func (mr *MockStorageLayerInterfaceMockRecorder) Del(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Del", reflect.TypeOf((*MockStorageLayerInterface)(nil).Del), arg0, arg1)
}

// Get mocks base method.
func (m *MockStorageLayerInterface) Get(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockStorageLayerInterfaceMockRecorder) Get(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockStorageLayerInterface)(nil).Get), arg0, arg1)
}

// Set mocks base method.
func (m *MockStorageLayerInterface) Set(arg0 context.Context, arg1, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockStorageLayerInterfaceMockRecorder) Set(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockStorageLayerInterface)(nil).Set), arg0, arg1, arg2)
}
